import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav>
          <ul className='flex justify-center gap-[20px] mb-4'>
            <li><Link href={"/about"}>About</Link></li>
            <li><Link href={"/blog"}>Blog</Link></li>
            <li><Link href={"/product"}>Products</Link></li>
            <li><Link href={"/profile"}>Profile</Link></li>
          </ul>
        </nav> */}
        {children}
      </body>
    </html>
  )
}
